# Use postgres/example user/password credentials
version: '3.9'

services:
  postgresdb:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file: ".env"
    ports:
      - "5433:5433"
    command: -p 5433
